model_train_type = "flux-lora"
pretrained_model_name_or_path = "C:/AI Tech/models/unet/FLUX/flux1-dev2pro.safetensors"
ae = "C:/AI Tech/models/vae/flux_ae.safetensors"
clip_l = "C:/AI Tech/models/clip/clip_l.safetensors"
t5xxl = "C:/AI Tech/models/clip/t5xxl_fp8_e4m3fn.safetensors"
timestep_sampling = "sigmoid"
sigmoid_scale = 1
model_prediction_type = "raw"
discrete_flow_shift = 1
loss_type = "l2"
guidance_scale = 1
train_t5xxl = false
train_data_dir = "E:/Design/Styles/anime01cxt/gemini"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 1536
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "anime01cxt"
output_dir = "E:/Design/loras/anime01cxt"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 2
save_state = false
max_train_epochs = 16
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.00001
lr_scheduler = "constant"
lr_warmup_steps = 0
optimizer_type = "AdamW8bit"
network_module = "networks.lora_flux"
network_dim = 16
network_alpha = 8
log_with = "tensorboard"
log_prefix = "anime01cxt"
log_tracker_name = "anime01cxt"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
seed = 42
clip_skip = 2
mixed_precision = "bf16"
sdpa = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = true
fp8_base = true
fp8_base_unet = true
randomly_choice_prompt = false
positive_prompts = ""
negative_prompts = ""
sample_width = 1024
sample_height = 1024
sample_cfg = 3.5
sample_seed = 42
sample_steps = 24
lr_scheduler_num_cycles = 4
